namespace HoU.GuildBot.DAL.Discord.Modules;

[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
[Group("wowretail", "WoW retail related commands.")]
public class WowRetailModule : InteractionModuleBase<SocketInteractionContext>
{
    private readonly IImageProvider _imageProvider;
    private readonly ILogger<WowRetailModule> _logger;

    public WowRetailModule(IImageProvider imageProvider,
                           ILogger<WowRetailModule> logger)
    {
        _imageProvider = imageProvider;
        _logger = logger;
    }
    
    [SlashCommand("chart", "Shows various charts related to WoW retail member roles.", runMode: RunMode.Async)]
    [AllowedRoles(Role.AnyGuildMember)]
    public async Task GetWowRetailRolesChartAsync(ChartType chartType)
    {
        await DeferAsync();
        try
        {
            Func<Stream> getImage = chartType switch
            {
                ChartType.PlayStyles => () => _imageProvider.CreateWowRetailPlayStyleDistributionImage(),
                _ => throw new NotSupportedException($"Chart type {chartType} is not supported.")
            };
            await using var imageStream = getImage();
            await Context.Interaction.FollowupWithFileAsync(imageStream, "chart.png");
        }
        catch (Exception e)
        {
            _logger.LogError(e, "Failed to create {ChartType} chart", chartType);
            await FollowupAsync("Failed to create chart.");
        }
    }

    /// <summary>
    /// Chart types that can be generated by <see cref="WowRetailModule.GetWowRetailRolesChartAsync"/>.
    /// </summary>
    public enum ChartType
    {
        PlayStyles = 1
    }
}