GRANT SELECT, INSERT ON [hou].[User] TO [hou-guildbot];
GRANT SELECT, INSERT, UPDATE, DELETE ON [hou].[UserInfo] TO [hou-guildbot];
GRANT SELECT, INSERT, DELETE ON [hou].[Vacation] TO [hou-guildbot];
GRANT SELECT, INSERT, UPDATE, DELETE ON [config].[Game] TO [hou-guildbot];
GRANT SELECT, INSERT, UPDATE, DELETE ON [config].[GameRole] TO [hou-guildbot];
GRANT SELECT, INSERT ON [config].[ScheduledReminder] TO [hou-guildbot];
GRANT SELECT, INSERT ON [config].[ScheduledReminderMention] TO [hou-guildbot];
GRANT SELECT ON [config].[Message] TO [hou-guildbot];
GRANT SELECT ON [config].[DiscordMapping] TO [hou-guildbot];
GRANT SELECT ON [config].[SpamProtectedChannel] TO [hou-guildbot];
GRANT SELECT ON [config].[DesiredTimeZone] TO [hou-guildbot];
GRANT SELECT ON [config].[UnitsEndpoint] TO [hou-guildbot];