// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HoU.GuildBot.DAL.Database.Model
{
    public partial class DesiredTimeZone
    {
        public string DesiredTimeZoneKey { get; set; }
        public string InvariantDisplayName { get; set; }
    }
}