// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HoU.GuildBot.DAL.Database.Model
{
    public partial class DiscordMapping
    {
        public string DiscordMappingKey { get; set; }
        public decimal DiscordID { get; set; }
    }
}