// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace HoU.GuildBot.DAL.Database.Model
{
    public partial class HandOfUnityContext : DbContext
    {
        public HandOfUnityContext()
        {
        }

        public HandOfUnityContext(DbContextOptions<HandOfUnityContext> options)
            : base(options)
        {
        }

        public virtual DbSet<DesiredTimeZone> DesiredTimeZone { get; set; }
        public virtual DbSet<DiscordMapping> DiscordMapping { get; set; }
        public virtual DbSet<FlywaySchemaHistory> FlywaySchemaHistory { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<GameRole> GameRole { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<ScheduledReminder> ScheduledReminder { get; set; }
        public virtual DbSet<ScheduledReminderMention> ScheduledReminderMention { get; set; }
        public virtual DbSet<SpamProtectedChannel> SpamProtectedChannel { get; set; }
        public virtual DbSet<UnitsEndpoint> UnitsEndpoint { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserBirthday> UserBirthday { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<Vacation> Vacation { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DesiredTimeZone>(entity =>
            {
                entity.HasKey(e => e.DesiredTimeZoneKey)
                    .HasName("desired_time_zone_pkey");

                entity.ToTable("desired_time_zone", "config");

                entity.Property(e => e.DesiredTimeZoneKey)
                    .HasMaxLength(128)
                    .HasColumnName("desired_time_zone_key");

                entity.Property(e => e.InvariantDisplayName)
                    .IsRequired()
                    .HasMaxLength(1024)
                    .HasColumnName("invariant_display_name");
            });

            modelBuilder.Entity<DiscordMapping>(entity =>
            {
                entity.HasKey(e => e.DiscordMappingKey)
                    .HasName("discord_mapping_pkey");

                entity.ToTable("discord_mapping", "config");

                entity.Property(e => e.DiscordMappingKey)
                    .HasMaxLength(64)
                    .HasColumnName("discord_mapping_key");

                entity.Property(e => e.DiscordId)
                    .HasPrecision(20)
                    .HasColumnName("discord_id");
            });

            modelBuilder.Entity<FlywaySchemaHistory>(entity =>
            {
                entity.HasKey(e => e.InstalledRank)
                    .HasName("flyway_schema_history_pk");

                entity.ToTable("flyway_schema_history", "config");

                entity.HasIndex(e => e.Success, "flyway_schema_history_s_idx");

                entity.Property(e => e.InstalledRank)
                    .ValueGeneratedNever()
                    .HasColumnName("installed_rank");

                entity.Property(e => e.Checksum).HasColumnName("checksum");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnName("description");

                entity.Property(e => e.ExecutionTime).HasColumnName("execution_time");

                entity.Property(e => e.InstalledBy)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("installed_by");

                entity.Property(e => e.InstalledOn)
                    .HasColumnType("timestamp without time zone")
                    .HasColumnName("installed_on")
                    .HasDefaultValueSql("now()");

                entity.Property(e => e.Script)
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnName("script");

                entity.Property(e => e.Success).HasColumnName("success");

                entity.Property(e => e.Type)
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnName("type");

                entity.Property(e => e.Version)
                    .HasMaxLength(50)
                    .HasColumnName("version");
            });

            modelBuilder.Entity<Game>(entity =>
            {
                entity.ToTable("game", "config");

                entity.HasIndex(e => e.GameInterestRoleId, "idx_game_not_null_game_interest_role_id")
                    .IsUnique()
                    .HasFilter("(game_interest_role_id IS NOT NULL)");

                entity.HasIndex(e => e.PrimaryGameDiscordRoleId, "uq_game_primary_game_discord_role_id")
                    .IsUnique();

                entity.Property(e => e.GameId)
                    .HasColumnName("game_id")
                    .UseIdentityAlwaysColumn();

                entity.Property(e => e.GameInterestRoleId)
                    .HasPrecision(20)
                    .HasColumnName("game_interest_role_id");

                entity.Property(e => e.IncludeInGamesMenu).HasColumnName("include_in_games_menu");

                entity.Property(e => e.IncludeInGuildMembersStatistic).HasColumnName("include_in_guild_members_statistic");

                entity.Property(e => e.ModifiedAtTimestamp).HasColumnName("modified_at_timestamp");

                entity.Property(e => e.ModifiedByUserId).HasColumnName("modified_by_user_id");

                entity.Property(e => e.PrimaryGameDiscordRoleId)
                    .HasPrecision(20)
                    .HasColumnName("primary_game_discord_role_id");

                entity.HasOne(d => d.ModifiedByUser)
                    .WithMany(p => p.Game)
                    .HasForeignKey(d => d.ModifiedByUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_game_user");
            });

            modelBuilder.Entity<GameRole>(entity =>
            {
                entity.ToTable("game_role", "config");

                entity.HasIndex(e => e.DiscordRoleId, "uq_game_role_discord_role_id")
                    .IsUnique();

                entity.Property(e => e.GameRoleId)
                    .HasColumnName("game_role_id")
                    .UseIdentityAlwaysColumn();

                entity.Property(e => e.DiscordRoleId)
                    .HasPrecision(20)
                    .HasColumnName("discord_role_id");

                entity.Property(e => e.GameId).HasColumnName("game_id");

                entity.Property(e => e.ModifiedAtTimestamp).HasColumnName("modified_at_timestamp");

                entity.Property(e => e.ModifiedByUserId).HasColumnName("modified_by_user_id");

                entity.HasOne(d => d.Game)
                    .WithMany(p => p.GameRole)
                    .HasForeignKey(d => d.GameId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_game_role_game_game_id");

                entity.HasOne(d => d.ModifiedByUser)
                    .WithMany(p => p.GameRole)
                    .HasForeignKey(d => d.ModifiedByUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_game_role_user_modified_by_user_id");
            });

            modelBuilder.Entity<Message>(entity =>
            {
                entity.ToTable("message", "config");

                entity.HasIndex(e => e.Name, "idx_message_name_inc_content")
                    .IsUnique();

                entity.Property(e => e.MessageId)
                    .HasColumnName("message_id")
                    .UseIdentityAlwaysColumn();

                entity.Property(e => e.Content)
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnName("content");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnName("description");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnName("name");
            });

            modelBuilder.Entity<ScheduledReminder>(entity =>
            {
                entity.ToTable("scheduled_reminder", "config");

                entity.Property(e => e.ScheduledReminderId)
                    .HasColumnName("scheduled_reminder_id")
                    .UseIdentityAlwaysColumn();

                entity.Property(e => e.CronSchedule)
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnName("cron_schedule");

                entity.Property(e => e.DiscordChannelId)
                    .HasPrecision(20)
                    .HasColumnName("discord_channel_id");

                entity.Property(e => e.Text)
                    .IsRequired()
                    .HasMaxLength(2048)
                    .HasColumnName("text");
            });

            modelBuilder.Entity<ScheduledReminderMention>(entity =>
            {
                entity.ToTable("scheduled_reminder_mention", "config");

                entity.Property(e => e.ScheduledReminderMentionId)
                    .HasColumnName("scheduled_reminder_mention_id")
                    .UseIdentityAlwaysColumn();

                entity.Property(e => e.DiscordRoleId)
                    .HasPrecision(20)
                    .HasColumnName("discord_role_id");

                entity.Property(e => e.DiscordUserId)
                    .HasPrecision(20)
                    .HasColumnName("discord_user_id");

                entity.Property(e => e.ScheduledReminderId).HasColumnName("scheduled_reminder_id");

                entity.HasOne(d => d.ScheduledReminder)
                    .WithMany(p => p.ScheduledReminderMention)
                    .HasForeignKey(d => d.ScheduledReminderId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_scheduled_reminder_mention_scheduled_reminder");
            });

            modelBuilder.Entity<SpamProtectedChannel>(entity =>
            {
                entity.ToTable("spam_protected_channel", "config");

                entity.Property(e => e.SpamProtectedChannelId)
                    .HasPrecision(20)
                    .HasColumnName("spam_protected_channel_id");

                entity.Property(e => e.HardCap).HasColumnName("hard_cap");

                entity.Property(e => e.SoftCap).HasColumnName("soft_cap");
            });

            modelBuilder.Entity<UnitsEndpoint>(entity =>
            {
                entity.ToTable("units_endpoint", "config");

                entity.HasIndex(e => e.BaseAddress, "uq_base_address")
                    .IsUnique();

                entity.Property(e => e.UnitsEndpointId)
                    .HasColumnName("units_endpoint_id")
                    .UseIdentityAlwaysColumn();

                entity.Property(e => e.BaseAddress)
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnName("base_address");

                entity.Property(e => e.ConnectToNotificationsHub).HasColumnName("connect_to_notifications_hub");

                entity.Property(e => e.ConnectToRestApi).HasColumnName("connect_to_rest_api");

                entity.Property(e => e.Secret)
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnName("secret");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.ToTable("user", "hou");

                entity.HasIndex(e => e.DiscordUserId, "idx_user_discord_user_id")
                    .IsUnique();

                entity.Property(e => e.UserId)
                    .HasColumnName("user_id")
                    .UseIdentityAlwaysColumn();

                entity.Property(e => e.DiscordUserId)
                    .HasPrecision(20)
                    .HasColumnName("discord_user_id");
            });

            modelBuilder.Entity<UserBirthday>(entity =>
            {
                entity.HasKey(e => e.UserId)
                    .HasName("user_birthday_pkey");

                entity.ToTable("user_birthday", "hou");

                entity.Property(e => e.UserId)
                    .ValueGeneratedNever()
                    .HasColumnName("user_id");

                entity.Property(e => e.Day).HasColumnName("day");

                entity.Property(e => e.Month).HasColumnName("month");

                entity.HasOne(d => d.User)
                    .WithOne(p => p.UserBirthday)
                    .HasForeignKey<UserBirthday>(d => d.UserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_user_birthday_user");
            });

            modelBuilder.Entity<UserInfo>(entity =>
            {
                entity.HasKey(e => e.UserId)
                    .HasName("user_info_pkey");

                entity.ToTable("user_info", "hou");

                entity.Property(e => e.UserId)
                    .ValueGeneratedNever()
                    .HasColumnName("user_id");

                entity.Property(e => e.LastSeen).HasColumnName("last_seen");

                entity.HasOne(d => d.User)
                    .WithOne(p => p.UserInfo)
                    .HasForeignKey<UserInfo>(d => d.UserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_user_info_user");
            });

            modelBuilder.Entity<Vacation>(entity =>
            {
                entity.ToTable("vacation", "hou");

                entity.Property(e => e.VacationId)
                    .HasColumnName("vacation_id")
                    .UseIdentityAlwaysColumn();

                entity.Property(e => e.EndDate).HasColumnName("end_date");

                entity.Property(e => e.Note)
                    .HasMaxLength(1024)
                    .HasColumnName("note");

                entity.Property(e => e.StartDate).HasColumnName("start_date");

                entity.Property(e => e.UserId).HasColumnName("user_id");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.Vacation)
                    .HasForeignKey(d => d.UserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("fk_vacation_user");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}