// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HoU.GuildBot.DAL.Database.Model
{
    public partial class PersonalReminder
    {
        public int PersonalReminderID { get; set; }
        public string CronSchedule { get; set; }
        public decimal DiscordChannelID { get; set; }
        public decimal UserToRemind { get; set; }
        public string Text { get; set; }
    }
}