// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HoU.GuildBot.DAL.Database.Model
{
    public partial class ScheduledReminderMention
    {
        public int ScheduledReminderMentionID { get; set; }
        public int ScheduledReminderID { get; set; }
        public decimal? DiscordUserID { get; set; }
        public decimal? DiscordRoleID { get; set; }

        public virtual ScheduledReminder ScheduledReminder { get; set; }
    }
}