// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HoU.GuildBot.DAL.Database.Model
{
    public partial class ScheduledReminderMention
    {
        public int ScheduledReminderMentionId { get; set; }
        public int ScheduledReminderId { get; set; }
        public decimal? DiscordUserId { get; set; }
        public decimal? DiscordRoleId { get; set; }

        public virtual ScheduledReminder ScheduledReminder { get; set; }
    }
}