// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HoU.GuildBot.DAL.Database.Model
{
    public partial class SpamProtectedChannel
    {
        public decimal SpamProtectedChannelId { get; set; }
        public int SoftCap { get; set; }
        public int HardCap { get; set; }
    }
}