// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HoU.GuildBot.DAL.Database.Model
{
    public partial class UnitsEndpoint
    {
        public int UnitsEndpointId { get; set; }
        public string BaseAddress { get; set; }
        public string Secret { get; set; }
        public bool ConnectToRestApi { get; set; }
        public bool ConnectToNotificationsHub { get; set; }
    }
}