// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HoU.GuildBot.DAL.Database.Model
{
    public partial class UserInfo
    {
        public int UserId { get; set; }
        public DateTime LastSeen { get; set; }

        public virtual User User { get; set; }
    }
}